name: food_fly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  flutter_screenutil:
  responsive_builder:
  firebase_auth: ^4.7.1
  google_sign_in:
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.7.6
  cloud_firestore: ^4.8.3
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  easy_localization: ^3.0.5
  flutter_animate: ^4.2.0+1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  permission_handler: ^10.4.3
  file_picker:
  path:
  page_transition: ^2.1.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  dio:
  hive:
  hive_flutter:
  http:
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.2
  intl: ^0.18.0
  webview_flutter:
  razorpay_flutter: ^1.3.6

  awesome_dialog: ^3.2.0
  lottie: ^3.0.0

  uuid: ^3.0.5
  awesome_notifications: ^0.8.2
  just_the_tooltip: ^0.0.12
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:


flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/svg/
    - assets/lottie/
    - assets/images/png/
