// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJexXbNOTl524SbfZa8wOzAOX_svZajeQ',
    appId: '1:819838946571:android:743bb03cbf6b32ab3f660e',
    messagingSenderId: '819838946571',
    projectId: 'foodfly-baf3c',
    storageBucket: 'foodfly-baf3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmeIQ4Otghqzmn0vdIZAdeeqgRUuojeI',
    appId: '1:819838946571:ios:7883ce3452d55b7b3f660e',
    messagingSenderId: '819838946571',
    projectId: 'foodfly-baf3c',
    storageBucket: 'foodfly-baf3c.appspot.com',
    androidClientId: '819838946571-1i4vjffqfvuvjar4c8bumrcug00f63kh.apps.googleusercontent.com',
    iosClientId: '819838946571-mb868gdo8buuft0jifa817vah3iv92tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodFly',
  );
}
