// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_4caxvLLoPXLh9PeIjr-aZX_AaMqajU',
    appId: '1:220191486693:web:07487fc3d4554623a3da0c',
    messagingSenderId: '220191486693',
    projectId: 'foodyfly-4df9c',
    authDomain: 'foodyfly-4df9c.firebaseapp.com',
    storageBucket: 'foodyfly-4df9c.appspot.com',
    measurementId: 'G-QN161KQT29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPEt03_HfKBJW0bc3-mQu6ywZ6fG4hJpg',
    appId: '1:220191486693:android:aa659f1090da9dd3a3da0c',
    messagingSenderId: '220191486693',
    projectId: 'foodyfly-4df9c',
    storageBucket: 'foodyfly-4df9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmX2cRiQRN09OTkU3GsvTshFJ73j7ppU4',
    appId: '1:220191486693:ios:3ecf3d062467ab54a3da0c',
    messagingSenderId: '220191486693',
    projectId: 'foodyfly-4df9c',
    storageBucket: 'foodyfly-4df9c.appspot.com',
    iosClientId: '220191486693-sldo6ck0iscps8t4cjnneo0hb7provo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodFly',
  );
}
