import 'package:easy_localization/easy_localization.dart';
import 'package:food_fly/ui/utils/theme/theme.dart';

final appStringController =
    ChangeNotifierProvider<AppString>((ref) => AppString());

class AppString extends ChangeNotifier {
  String keyFoodFly = 'keyFoodFly'.tr();
  String keyFindYourBestMeal = "keyFindYourBestMeal".tr();
  String keySignIn = "keySignIn".tr();
  String keyForgetPassword = "keyForgetPassword".tr();
  String keyORContinueWith = "keyORContinueWith".tr();
  String keyGoogle = "keyGoogle".tr();
  String keyFacebook = "keyFacebook".tr();
  String keyCreateAnAccount = "keyCreateAnAccount".tr();
  String keySignUp = "keySignUp".tr();
  String keyRegisterAndEat = "keyRegisterAndEat".tr();
  String keyAddPhoto = "keyAddPhoto".tr();
  String keyFullName = "keyFullName".tr();
  String keyTypeYourFullName = "keyTypeYourFullName".tr();
  String keyEmailAddress = "keyEmailAddress".tr();
  String keyTypeYourEmailAddress = "keyTypeYourEmailAddress".tr();
  String keyPassword = "keyPassword".tr();
  String keyTypeYourPassword = "keyTypeYourPassword".tr();
  String keyContinue = "keyContinue".tr();
  String keyIAlreadyHaveAnAccount = "keyIAlreadyHaveAnAccount".tr();
  String keyLogIn = "keyLogIn".tr();
  String keyAddress = "keyAddress".tr();
  String keyMakeSureItsValid = "keyMakeSureItsValid".tr();
  String keyPhoneNo = "keyPhoneNo".tr();
  String keyTypeYourPhoneNumber = "keyTypeYourPhoneNumber".tr();
  String keyTypeYourAddress = "keyTypeYourAddress".tr();
  String keyPostalCode = "keyPostalCode".tr();
  String keyTypeYourPostalCode = "keyTypeYourPostalCode".tr();
  String keyCity = "keyCity".tr();
  String keySelectYourCity = "keySelectYourCity".tr();
  String keySignUpNow = "keySignUpNow".tr();
  String keyYeahCompleted = "keyYeahCompleted".tr();
  String keyGreetingMsg = "keyGreetingMsg".tr();
  String keyFindFoods = "keyFindFoods".tr();
  String keyLetsGetSomeFoods = "keyLetsGetSomeFoods".tr();
  String keyNewTaste = "keyNewTaste".tr();
  String keyPopular = "keyPopular".tr();
  String keyRecommended = "keyRecommended".tr();
  String keyIngredients = "keyIngredients".tr();
  String keyOrderNow = "keyOrderNow".tr();
  String keyTotalPrice = "keyTotalPrice".tr();
  String keyPayment = "keyPayment".tr();
  String keyYouDeserveBetterMeal = "keyYouDeserveBetterMeal".tr();
  String keyItemOrdered = "keyItemOrdered".tr();
  String keyDetailsTransaction = "keyDetailsTransaction".tr();
  String keyDriver = "keyDriver".tr();
  String keyTax = "keyTax".tr();
  String keyDeliverTo = "keyDeliverTo".tr();
  String keyName = "keyName".tr();
  String keyHouseNo = "keyHouseNo".tr();
  String keyCheckoutNow = "keyCheckoutNow".tr();
  String keyYourOrders = "keyYourOrders".tr();
  String keyWaitForTheBestMeal = "keyWaitForTheBestMeal".tr();
  String keyInProgress = "keyInProgress".tr();
  String keyPastOrders = "keyPastOrders".tr();
  String keyAccount = "keyAccount".tr();
  String keyFoodMarket = "keyFoodMarket".tr();
  String keyEditProfile = "keyEditProfile".tr();
  String keyHomeAddress = "keyHomeAddress".tr();
  String keySecurity = "keySecurity".tr();
  String keyPayments = "keyPayments".tr();
  String keyRateApp = "keyRateApp".tr();
  String keyHelpCenter = "keyHelpCenter".tr();
  String keyPrivacyPolicy = "keyPrivacyPolicy".tr();
  String keyTermsConditions = "keyTermsConditions".tr();
  String keyYouHaveMadeOrder = "keyYouHaveMadeOrder".tr();
  String keyOrderedFoodSummary = "keyOrderedFoodSummary".tr();
  String keyOrderOtherFoods = "keyOrderOtherFoods".tr();
  String keyViewMyOrder = "keyViewMyOrder".tr();
  String keyOuchHungry = "keyOuchHungry".tr();
  String keyFindFoodSummary = "keyFindFoodSummary".tr();
  String keyOrderStatus = "keyOrderStatus".tr();
  String keyCancelMyOrder = "keyCancelMyOrder".tr();

  updateString() {
    keyFoodFly = 'keyFoodFly'.tr();
    keyFindYourBestMeal = "keyFindYourBestMeal".tr();
    keySignIn = "keySignIn".tr();
    keyForgetPassword = "keyForgetPassword".tr();
    keyORContinueWith = "keyORContinueWith".tr();
    keyGoogle = "keyGoogle".tr();
    keyFacebook = "keyFacebook".tr();
    keyCreateAnAccount = "keyCreateAnAccount".tr();
    keySignUp = "keySignUp".tr();
    keyRegisterAndEat = "keyRegisterAndEat".tr();
    keyAddPhoto = "keyAddPhoto".tr();
    keyFullName = "keyFullName".tr();
    keyTypeYourFullName = "keyTypeYourFullName".tr();
    keyEmailAddress = "keyEmailAddress".tr();
    keyTypeYourEmailAddress = "keyTypeYourEmailAddress".tr();
    keyPassword = "keyPassword".tr();
    keyTypeYourPassword = "keyTypeYourPassword".tr();
    keyContinue = "keyContinue".tr();
    keyIAlreadyHaveAnAccount = "keyIAlreadyHaveAnAccount".tr();
    keyLogIn = "keyLogIn".tr();
    keyAddress = "keyAddress".tr();
    keyMakeSureItsValid = "keyMakeSureItsValid".tr();
    keyPhoneNo = "keyPhoneNo".tr();
    keyTypeYourPhoneNumber = "keyTypeYourPhoneNumber".tr();
    keyTypeYourAddress = "keyTypeYourAddress".tr();
    keyPostalCode = "keyPostalCode".tr();
    keyTypeYourPostalCode = "keyTypeYourPostalCode".tr();
    keyCity = "keyCity".tr();
    keySelectYourCity = "keySelectYourCity".tr();
    keySignUpNow = "keySignUpNow".tr();
    keyYeahCompleted = "keyYeahCompleted".tr();
    keyGreetingMsg = "keyGreetingMsg".tr();
    keyFindFoods = "keyFindFoods".tr();
    keyLetsGetSomeFoods = "keyLetsGetSomeFoods".tr();
    keyNewTaste = "keyNewTaste".tr();
    keyPopular = "keyPopular".tr();
    keyRecommended = "keyRecommended".tr();
    keyIngredients = "keyIngredients".tr();
    keyOrderNow = "keyOrderNow".tr();
    keyTotalPrice = "keyTotalPrice".tr();
    keyPayment = "keyPayment".tr();
    keyYouDeserveBetterMeal = "keyYouDeserveBetterMeal".tr();
    keyItemOrdered = "keyItemOrdered".tr();
    keyDetailsTransaction = "keyDetailsTransaction".tr();
    keyDriver = "keyDriver".tr();
    keyTax = "keyTax".tr();
    keyDeliverTo = "keyDeliverTo".tr();
    keyName = "keyName".tr();
    keyHouseNo = "keyHouseNo".tr();
    keyCheckoutNow = "keyCheckoutNow".tr();
    keyYourOrders = "keyYourOrders".tr();
    keyWaitForTheBestMeal = "keyWaitForTheBestMeal".tr();
    keyInProgress = "keyInProgress".tr();
    keyPastOrders = "keyPastOrders".tr();
    keyAccount = "keyAccount".tr();
    keyFoodMarket = "keyFoodMarket".tr();
    keyEditProfile = "keyEditProfile".tr();
    keyHomeAddress = "keyHomeAddress".tr();
    keySecurity = "keySecurity".tr();
    keyPayments = "keyPayments".tr();
    keyRateApp = "keyRateApp".tr();
    keyHelpCenter = "keyHelpCenter".tr();
    keyPrivacyPolicy = "keyPrivacyPolicy".tr();
    keyTermsConditions = "keyTermsConditions".tr();
    keyYouHaveMadeOrder = "keyYouHaveMadeOrder".tr();
    keyOrderedFoodSummary = "keyOrderedFoodSummary".tr();
    keyOrderOtherFoods = "keyOrderOtherFoods".tr();
    keyViewMyOrder = "keyViewMyOrder".tr();
    keyOuchHungry = "keyOuchHungry".tr();
    keyFindFoodSummary = "keyFindFoodSummary".tr();
    keyOrderStatus = "keyOrderStatus".tr();
    keyCancelMyOrder = "keyCancelMyOrder".tr();
  }

  updateLanguage(BuildContext context) async {
    if (context.locale == const Locale('en')) {
      await context.setLocale(const Locale('gu'));
    } else {
      await context.setLocale(const Locale('en'));
    }
    updateString();
    notifyListeners();
  }
}
